denial_constraints = [
    [('t1.local_code', '==', 't2.local_code'), ('t1.type', '==', 't2.type'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.continent', '==', 't2.continent'), ('t1.type', '==', 't2.type'), ('t1.wikipedia_link', '==', 't2.wikipedia_link'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.local_code', '==', 't2.local_code'), ('t1.wikipedia_link', '!=', 't2.wikipedia_link')],
    [('t1.continent', '==', 't2.continent'), ('t1.wikipedia_link', '==', 't2.wikipedia_link'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.gps_code', '==', 't2.gps_code'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.local_code', '==', 't2.local_code'), ('t1.scheduled_service', '==', 't2.scheduled_service'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.continent', '==', 't2.continent'), ('t1.keywords', '==', 't2.keywords'), ('t1.iso_country', '!=', 't2.iso_country')],
    [('t1.local_code', '==', 't2.local_code'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.keywords', '==', 't2.keywords'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.continent', '==', 't2.continent'), ('t1.keywords', '==', 't2.keywords'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.keywords', '==', 't2.keywords'), ('t1.scheduled_service', '!=', 't2.scheduled_service')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.wikipedia_link', '!=', 't2.wikipedia_link')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.scheduled_service', '!=', 't2.scheduled_service')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.type', '!=', 't2.type')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.municipality', '==', 't2.municipality'), ('t1.local_code', '!=', 't2.local_code')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.continent', '==', 't2.continent'), ('t1.type', '==', 't2.type'), ('t1.scheduled_service', '!=', 't2.scheduled_service')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.wikipedia_link', '!=', 't2.wikipedia_link')],
    [('t1.type', '==', 't2.type'), ('t1.scheduled_service', '!=', 't2.scheduled_service')],
    [('t1.continent', '==', 't2.continent'), ('t1.type', '==', 't2.type'), ('t1.iso_country', '!=', 't2.iso_country')],
    [('t1.continent', '==', 't2.continent'), ('t1.iso_country', '!=', 't2.iso_country')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.local_code', '!=', 't2.local_code')],
    [('t1.elevation_ft', '==', 't2.elevation_ft'), ('t1.gps_code', '!=', 't2.gps_code')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.type', '==', 't2.type'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.type', '==', 't2.type'), ('t1.wikipedia_link', '!=', 't2.wikipedia_link')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.type', '==', 't2.type'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.type', '==', 't2.type'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.home_link', '!=', 't2.home_link')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.iata_code', '!=', 't2.iata_code')],
    [('t1.iso_country', '==', 't2.iso_country'), ('t1.wikipedia_link', '!=', 't2.wikipedia_link')],
    [('t1.continent', '==', 't2.continent'), ('t1.type', '==', 't2.type'), ('t1.keywords', '!=', 't2.keywords')],
    [('t1.continent', '==', 't2.continent'), ('t1.type', '==', 't2.type'), ('t1.home_link', '!=', 't2.home_link')],
]
