denial_constraints = [
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '==', 't2.sex'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '==', 't2.sex'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '==', 't2.sex'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.sex', '==', 't2.sex'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.occupation', '==', 't2.occupation'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.sex', '==', 't2.sex'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '==', 't2.sex'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.occupation', '==', 't2.occupation'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '==', 't2.sex'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.age', '==', 't2.age'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.occupation', '==', 't2.occupation'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.occupation', '==', 't2.occupation'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.race', '==', 't2.race'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.workclass', '==', 't2.workclass'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.class', '==', 't2.class'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.race', '==', 't2.race'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.sex', '==', 't2.sex'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.sex', '!=', 't2.sex')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.sex', '==', 't2.sex'), ('t1.relationship', '!=', 't2.relationship')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.occupation', '==', 't2.occupation'), ('t1.sex', '!=', 't2.sex')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.relationship', '==', 't2.relationship'), ('t1.class', '!=', 't2.class')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.class', '!=', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '==', 't2.workclass'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.class', '!=', 't2.class')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.class', '!=', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.marital_status', '!=', 't2.marital_status')],
    [('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.education', '==', 't2.education'), ('t1.sex', '!=', 't2.sex')],
    [('t1.education_num', '==', 't2.education_num'), ('t1.hours_per_week', '==', 't2.hours_per_week'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.sex', '!=', 't2.sex')],
    [('t1.education', '==', 't2.education'), ('t1.relationship', '==', 't2.relationship'), ('t1.workclass', '==', 't2.workclass'), ('t1.class', '!=', 't2.class')],
]
