# Parsed denial constraints for Airport
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.id', '==', 't2.id')],
    [('t1.ident', '==', 't2.ident')],
    [('t1.name', '==', 't2.name'), ('t1.elevation_ft', '!=', 't2.elevation_ft'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country')],
    [('t1.name', '==', 't2.name'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.local_code', '!=', 't2.local_code')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.local_code', '!=', 't2.local_code')],
    [('t1.name', '==', 't2.name'), ('t1.latitude_deg', '!=', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.name', '==', 't2.name'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.gps_code', '!=', 't2.gps_code')],
    [('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.gps_code', '!=', 't2.gps_code')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.iata_code', '==', 't2.iata_code')],
    [('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '!=', 't2.longitude_deg'), ('t1.elevation_ft', '!=', 't2.elevation_ft'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.wikipedia_link', '==', 't2.wikipedia_link')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.gps_code', '!=', 't2.gps_code'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.iata_code', '==', 't2.iata_code'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.local_code', '!=', 't2.local_code'), ('t1.wikipedia_link', '==', 't2.wikipedia_link'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.iata_code', '==', 't2.iata_code'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.wikipedia_link', '==', 't2.wikipedia_link'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.iso_country', '!=', 't2.iso_country'), ('t1.iso_region', '==', 't2.iso_region')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.iata_code', '==', 't2.iata_code')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.home_link', '==', 't2.home_link')],
    [('t1.type', '!=', 't2.type'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.wikipedia_link', '==', 't2.wikipedia_link')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.elevation_ft', '!=', 't2.elevation_ft'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.wikipedia_link', '==', 't2.wikipedia_link')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.local_code', '!=', 't2.local_code')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.iata_code', '==', 't2.iata_code')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.home_link', '==', 't2.home_link')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.scheduled_service', '==', 't2.scheduled_service')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.wikipedia_link', '==', 't2.wikipedia_link')],
    [('t1.type', '!=', 't2.type'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.iata_code', '==', 't2.iata_code')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.municipality', '!=', 't2.municipality')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.elevation_ft', '!=', 't2.elevation_ft')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.type', '!=', 't2.type'), ('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.wikipedia_link', '==', 't2.wikipedia_link')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.continent', '!=', 't2.continent'), ('t1.iso_country', '==', 't2.iso_country'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.type', '!=', 't2.type'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.scheduled_service', '!=', 't2.scheduled_service'), ('t1.wikipedia_link', '==', 't2.wikipedia_link'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.type', '!=', 't2.type'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '==', 't2.longitude_deg'), ('t1.iso_region', '!=', 't2.iso_region'), ('t1.keywords', '==', 't2.keywords')],
    [('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '!=', 't2.longitude_deg'), ('t1.elevation_ft', '>', 't2.elevation_ft'), ('t1.iso_region', '!=', 't2.iso_region')],
    [('t1.name', '==', 't2.name'), ('t1.latitude_deg', '==', 't2.latitude_deg'), ('t1.longitude_deg', '!=', 't2.longitude_deg'), ('t1.elevation_ft', '<', 't2.elevation_ft'), ('t1.iso_region', '!=', 't2.iso_region')],
]
