denial_constraints = [
    [('t1.dayofmonth', '==', 't2.dayofmonth'), ('t1.flightdate', '!=', 't2.flightdate')],
    [('t1.dayofmonth', '==', 't2.dayofmonth'), ('t1.dayofweek', '!=', 't2.dayofweek')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originwac', '!=', 't2.originwac')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originstatename', '!=', 't2.originstatename')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originstatefips', '!=', 't2.originstatefips')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originstate', '!=', 't2.originstate')],
    [('t1.origincityname', '==', 't2.origincityname'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.origincityname', '==', 't2.origincityname'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.origincityname', '==', 't2.origincityname'), ('t1.origin', '!=', 't2.origin')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.origin', '!=', 't2.origin')],
    [('t1.origincitymarketid', '==', 't2.origincitymarketid'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originwac', '==', 't2.originwac'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.originstate', '==', 't2.originstate'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originwac', '==', 't2.originwac'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.originwac', '==', 't2.originwac'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstate', '==', 't2.originstate'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstate', '==', 't2.originstate'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.originstatefips', '==', 't2.originstatefips'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.originstatename', '==', 't2.originstatename'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincitymarketid', '!=', 't2.origincitymarketid')],
    [('t1.originstate', '==', 't2.originstate'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.originstatefips', '==', 't2.originstatefips'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originwac', '==', 't2.originwac'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.originstatename', '==', 't2.originstatename'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstate', '==', 't2.originstate'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstate', '==', 't2.originstate'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.originwac', '==', 't2.originwac'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originwac', '==', 't2.originwac'), ('t1.origincityname', '!=', 't2.origincityname')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origin', '!=', 't2.origin')],
    [('t1.originstatename', '==', 't2.originstatename'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origin', '!=', 't2.origin')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstate', '==', 't2.originstate'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstate', '==', 't2.originstate'), ('t1.origin', '!=', 't2.origin')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.originstatename', '==', 't2.originstatename'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.originstatename', '==', 't2.originstatename'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.originstate', '==', 't2.originstate'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origin', '!=', 't2.origin')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.originstate', '==', 't2.originstate'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.originstate', '==', 't2.originstate'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originwac', '==', 't2.originwac'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originwac', '==', 't2.originwac'), ('t1.originairportid', '!=', 't2.originairportid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originwac', '==', 't2.originwac'), ('t1.origin', '!=', 't2.origin')],
    [('t1.originstatefips', '==', 't2.originstatefips'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstate', '==', 't2.originstate'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origin', '!=', 't2.origin')],
    [('t1.originstatefips', '==', 't2.originstatefips'), ('t1.uniquecarrier', '==', 't2.uniquecarrier'), ('t1.origin', '!=', 't2.origin')],
    [('t1.airlineid', '==', 't2.airlineid'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.origin', '!=', 't2.origin')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatefips', '==', 't2.originstatefips'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstate', '==', 't2.originstate'), ('t1.originairportseqid', '!=', 't2.originairportseqid')],
    [('t1.carrier', '==', 't2.carrier'), ('t1.originstatename', '==', 't2.originstatename'), ('t1.origin', '!=', 't2.origin')],
]
