denial_constraints = [
    [('t1.DayOfMonth', '==', 't2.DayOfMonth'), ('t1.FlightDate', '!=', 't2.FlightDate')],
    [('t1.DayOfMonth', '==', 't2.DayOfMonth'), ('t1.DayOfWeek', '!=', 't2.DayOfWeek')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginWac', '!=', 't2.OriginWac')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginStateName', '!=', 't2.OriginStateName')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginStateFips', '!=', 't2.OriginStateFips')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginState', '!=', 't2.OriginState')],
    [('t1.OriginCityName', '==', 't2.OriginCityName'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.OriginCityName', '==', 't2.OriginCityName'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.OriginCityName', '==', 't2.OriginCityName'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.OriginCityMarketId', '==', 't2.OriginCityMarketId'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.OriginState', '==', 't2.OriginState'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.OriginWac', '==', 't2.OriginWac'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityMarketId', '!=', 't2.OriginCityMarketId')],
    [('t1.OriginState', '==', 't2.OriginState'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.OriginWac', '==', 't2.OriginWac'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginCityName', '!=', 't2.OriginCityName')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.OriginState', '==', 't2.OriginState'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.OriginState', '==', 't2.OriginState'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.OriginState', '==', 't2.OriginState'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.OriginAirportId', '!=', 't2.OriginAirportId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginWac', '==', 't2.OriginWac'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.UniqueCarrier', '==', 't2.UniqueCarrier'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.AirlineId', '==', 't2.AirlineId'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.Origin', '!=', 't2.Origin')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateFips', '==', 't2.OriginStateFips'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginState', '==', 't2.OriginState'), ('t1.OriginAirportSeqId', '!=', 't2.OriginAirportSeqId')],
    [('t1.Carrier', '==', 't2.Carrier'), ('t1.OriginStateName', '==', 't2.OriginStateName'), ('t1.Origin', '!=', 't2.Origin')],
]
