# Parsed denial constraints for Hospital
# Generated automatically from raw constraints
# ["ProviderNumber", "HospitalName", "City", "State", "ZIPCode",
#                            "CountyName", "PhoneNumber", "HospitalType", "HospitalOwner",
#                            "EmergencyService", "Condition", "MeasureCode", "MeasureName", "Sample",
#                            "StateAvg"]
denial_constraints = [
    [('t1.measurecode', '!=', 't2.measurecode'), ('t1.MeasureName', '==', 't2.MeasureName')],
    [('t1.measurecode', '==', 't2.measurecode'), ('t1.MeasureName', '!=', 't2.MeasureName')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalName', '!=', 't2.HospitalName')],
    [('t1.ZIPcode', '!=', 't2.ZIPcode'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.ZIPcode', '!=', 't2.ZIPcode')],
    [('t1.measurecode', '!=', 't2.measurecode'), ('t1.StateAvg', '==', 't2.StateAvg')],
    [('t1.MeasureName', '!=', 't2.MeasureName'), ('t1.StateAvg', '==', 't2.StateAvg')],
    [('t1.City', '!=', 't2.City'), ('t1.ZIPcode', '==', 't2.ZIPcode')],
    [('t1.City', '!=', 't2.City'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.City', '!=', 't2.City')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.CountyName', '!=', 't2.CountyName')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
    [('t1.State', '==', 't2.State'), ('t1.MeasureName', '==', 't2.MeasureName'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.State', '==', 't2.State'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.Condition', '!=', 't2.Condition'), ('t1.measurecode', '==', 't2.measurecode')],
    [('t1.Condition', '!=', 't2.Condition'), ('t1.MeasureName', '==', 't2.MeasureName')],
    [('t1.Condition', '!=', 't2.Condition'), ('t1.StateAvg', '==', 't2.StateAvg')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.measurecode', '==', 't2.measurecode')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.MeasureName', '==', 't2.MeasureName')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.StateAvg', '==', 't2.StateAvg')],
    [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
    [('t1.ZIPcode', '==', 't2.ZIPcode'), ('t1.CountyName', '!=', 't2.CountyName'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber'), ('t1.HospitalOwner', '==', 't2.HospitalOwner')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.State', '==', 't2.State'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
    [('t1.ProviderNumber', '!=', 't2.ProviderNumber'), ('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '==', 't2.City'), ('t1.State', '==', 't2.State')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '==', 't2.City'), ('t1.State', '==', 't2.State'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '==', 't2.City'), ('t1.State', '==', 't2.State'), ('t1.ZIPcode', '!=', 't2.ZIPcode')],
    [('t1.ZIPcode', '==', 't2.ZIPcode'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.ZIPcode', '==', 't2.ZIPcode'), ('t1.MeasureName', '==', 't2.MeasureName'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.MeasureName', '==', 't2.MeasureName'), ('t1.StateAvg', '!=', 't2.StateAvg')],
    [('t1.ProviderNumber', '!=', 't2.ProviderNumber'), ('t1.HospitalName', '==', 't2.HospitalName'), ('t1.ZIPcode', '==', 't2.ZIPcode')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.ZIPcode', '==', 't2.ZIPcode'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber')],
    [('t1.ProviderNumber', '!=', 't2.ProviderNumber'), ('t1.HospitalName', '==', 't2.HospitalName'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '==', 't2.City'), ('t1.State', '==', 't2.State'), ('t1.CountyName', '!=', 't2.CountyName')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.ZIPcode', '==', 't2.ZIPcode'), ('t1.CountyName', '!=', 't2.CountyName')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.CountyName', '!=', 't2.CountyName'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.State', '==', 't2.State'), ('t1.CountyName', '==', 't2.CountyName'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
    [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '==', 't2.City'), ('t1.State', '==', 't2.State'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
    [('t1.State', '!=', 't2.State'), ('t1.StateAvg', '==', 't2.StateAvg')],
]
