# denial_constraints = [
#     [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.Sample', '==', 't2.Sample'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
#     [('t1.Condition', '==', 't2.Condition'), ('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
#     [('t1.Condition', '==', 't2.Condition'), ('t1.Sample', '==', 't2.Sample'), ('t1.HospitalType', '!=', 't2.HospitalType')],
#     [('t1.State', '==', 't2.State'), ('t1.HospitalType', '!=', 't2.HospitalType')],
# ]
denial_constraints = [[('t1.MeasureName', '!=', 't2.MeasureName'), ('t1.StateAvg', '==', 't2.StateAvg')],
                               [('t1.MeasureCode', '!=', 't2.MeasureCode'), ('t1.StateAvg', '==', 't2.StateAvg')],
                               [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.City', '!=', 't2.City')], [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.State', '!=', 't2.State')], [('t1.MeasureCode', '==', 't2.MeasureCode'), ('t1.MeasureName', '!=', 't2.MeasureName')], [('t1.MeasureName', '==', 't2.MeasureName'), ('t1.MeasureCode', '!=', 't2.MeasureCode')], [('t1.ZIPCode', '==', 't2.ZIPCode'), ('t1.City', '!=', 't2.City')], [('t1.StateAvg', '!=', 't2.StateAvg'), ('t1.State', '==', 't2.State'), ('t1.MeasureName', '==', 't2.MeasureName')], [('t1.Condition', '!=', 't2.Condition'), ('t1.StateAvg', '==', 't2.StateAvg')], [('t1.ZIPCode', '!=', 't2.ZIPCode'), ('t1.ProviderNumber', '==', 't2.ProviderNumber')], [('t1.StateAvg', '!=', 't2.StateAvg'), ('t1.State', '==', 't2.State'), ('t1.MeasureCode', '==', 't2.MeasureCode')], [('t1.Condition', '!=', 't2.Condition'), ('t1.MeasureCode', '==', 't2.MeasureCode')], [('t1.ZIPCode', '!=', 't2.ZIPCode'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')], [('t1.PhoneNumber', '!=', 't2.PhoneNumber'), ('t1.ProviderNumber', '==', 't2.ProviderNumber')], [('t1.State', '!=', 't2.State'), ('t1.StateAvg', '==', 't2.StateAvg')], [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.CountyName', '!=', 't2.CountyName')], [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')], [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.City', '!=', 't2.City')], [('t1.ZIPCode', '==', 't2.ZIPCode'), ('t1.State', '!=', 't2.State')], [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.State', '!=', 't2.State')], [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalName', '!=', 't2.HospitalName')], [('t1.Condition', '!=', 't2.Condition'), ('t1.MeasureName', '==', 't2.MeasureName')]]

