denial_constraints = [[('t1.MeasureCode', '!=', 't2.MeasureCode'), ('t1.MeasureName', '==', 't2.MeasureName')],
 [('t1.MeasureCode', '==', 't2.MeasureCode'), ('t1.MeasureName', '!=', 't2.MeasureName')],
 [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber')],
 [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalName', '!=', 't2.HospitalName')],
 [('t1.ZipCode', '!=', 't2.ZipCode'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
 [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.ProviderNumber', '==', 't2.ProviderNumber'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.State', '!=', 't2.State'), ('t1.PhoneNumber', '==', 't2.PhoneNumber')],
 [('t1.City', '!=', 't2.City'), ('t1.ZipCode', '==', 't2.ZipCode')],
 [('t1.State', '!=', 't2.State'), ('t1.ZipCode', '==', 't2.ZipCode')],
 [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.PhoneNumber', '!=', 't2.PhoneNumber')],
 [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.State', '!=', 't2.State')],
 [('t1.HospitalName', '==', 't2.HospitalName'), ('t1.City', '!=', 't2.City')],
 [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.PhoneNumber', '==', 't2.PhoneNumber'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.State', '!=', 't2.State')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.City', '!=', 't2.City')],
 [('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.State', '!=', 't2.State')],
 [('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.City', '!=', 't2.City')],
 [('t1.State', '==', 't2.State'), ('t1.City', '!=', 't2.City')],
 [('t1.Sample', '==', 't2.Sample'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.Sample', '==', 't2.Sample'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.Condition', '==', 't2.Condition'), ('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.Condition', '==', 't2.Condition'), ('t1.Sample', '==', 't2.Sample'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.State', '==', 't2.State'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.State', '==', 't2.State'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.City', '==', 't2.City'), ('t1.HospitalType', '!=', 't2.HospitalType')],
 [('t1.City', '==', 't2.City'), ('t1.HospitalOwner', '!=', 't2.HospitalOwner')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.EmergencyService', '==', 't2.EmergencyService'), ('t1.Sample', '!=', 't2.Sample')],
 [('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.EmergencyService', '==', 't2.EmergencyService'), ('t1.Sample', '!=', 't2.Sample')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.EmergencyService', '==', 't2.EmergencyService'), ('t1.Condition', '!=', 't2.Condition')],
 [('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.EmergencyService', '==', 't2.EmergencyService'), ('t1.Condition', '!=', 't2.Condition')],
 [('t1.HospitalType', '==', 't2.HospitalType'), ('t1.Condition', '==', 't2.Condition'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.HospitalOwner', '==', 't2.HospitalOwner'), ('t1.Condition', '==', 't2.Condition'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.Sample', '==', 't2.Sample'), ('t1.Condition', '==', 't2.Condition'), ('t1.EmergencyService', '!=', 't2.EmergencyService')],
 [('t1.State', '==', 't2.State'), ('t1.Condition', '==', 't2.Condition'), ('t1.HospitalType', '!=', 't2.HospitalType')]]
