# Parsed denial constraints for NCVoter
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.state', '!=', 't2.state')],
    [('t1.voter_id', '!=', 't2.voter_id'), ('t1.voter_reg_num', '==', 't2.voter_reg_num')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.voter_reg_num', '!=', 't2.voter_reg_num')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.last_name', '!=', 't2.last_name')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.last_name', '!=', 't2.last_name')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.first_name', '!=', 't2.first_name')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.first_name', '!=', 't2.first_name')],
    [('t1.street_address', '==', 't2.street_address'), ('t1.zip_code', '!=', 't2.zip_code')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.zip_code', '!=', 't2.zip_code')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.zip_code', '!=', 't2.zip_code')],
    [('t1.street_address', '==', 't2.street_address'), ('t1.city', '!=', 't2.city')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.city', '!=', 't2.city')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.city', '!=', 't2.city')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.register_date', '!=', 't2.register_date')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.register_date', '!=', 't2.register_date')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.age', '!=', 't2.age')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.age', '!=', 't2.age')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.download_month', '==', 't2.download_month')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.download_month', '==', 't2.download_month')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.full_phone_num', '==', 't2.full_phone_num')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.full_phone_num', '==', 't2.full_phone_num')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.gender', '!=', 't2.gender')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.gender', '!=', 't2.gender')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.age', '>', 't2.age')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.age', '<', 't2.age')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.age', '>', 't2.age')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.age', '<', 't2.age')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.birth_place', '!=', 't2.birth_place')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.birth_place', '!=', 't2.birth_place')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.middle_name', '==', 't2.middle_name')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.middle_name', '==', 't2.middle_name')],
    [('t1.first_name', '==', 't2.first_name'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.voter_id', '==', 't2.voter_id'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.voter_reg_num', '==', 't2.voter_reg_num'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.last_name', '!=', 't2.last_name'), ('t1.name_suffix', '!=', 't2.name_suffix'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.name_prefix', '!=', 't2.name_prefix'), ('t1.last_name', '!=', 't2.last_name'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.name_prefix', '!=', 't2.name_prefix'), ('t1.city', '!=', 't2.city'), ('t1.zip_code', '==', 't2.zip_code')],
    [('t1.name_suffix', '!=', 't2.name_suffix'), ('t1.age', '!=', 't2.age'), ('t1.street_address', '==', 't2.street_address'), ('t1.register_date', '!=', 't2.register_date')],
    [('t1.age', '!=', 't2.age'), ('t1.race', '!=', 't2.race'), ('t1.ethnic', '==', 't2.ethnic'), ('t1.street_address', '==', 't2.street_address')],
    [('t1.middle_name', '==', 't2.middle_name'), ('t1.last_name', '!=', 't2.last_name'), ('t1.street_address', '==', 't2.street_address'), ('t1.register_date', '!=', 't2.register_date')],
]
