denial_constraints = [
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.CustomerID', '!=', 't2.CustomerID')],
    [('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.InvoiceNo', '!=', 't2.InvoiceNo'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.Country', '!=', 't2.Country'), ('t1.UnitPrice', '==', 't2.UnitPrice'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Country', '!=', 't2.Country'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.InvoiceNo', '!=', 't2.InvoiceNo'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '!=', 't2.CustomerID'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '!=', 't2.CustomerID'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.Description', '!=', 't2.Description'), ('t1.Quantity', '!=', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.InvoiceDate', '!=', 't2.InvoiceDate'), ('t1.UnitPrice', '>', 't2.UnitPrice'), ('t1.Quantity', '<', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.UnitPrice', '==', 't2.UnitPrice'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '!=', 't2.CustomerID'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.UnitPrice', '==', 't2.UnitPrice'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '!=', 't2.CustomerID'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.Country', '!=', 't2.Country'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.InvoiceNo', '!=', 't2.InvoiceNo'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '==', 't2.CustomerID'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.InvoiceDate', '!=', 't2.InvoiceDate'), ('t1.UnitPrice', '>', 't2.UnitPrice'), ('t1.Description', '==', 't2.Description'), ('t1.Quantity', '<', 't2.Quantity')],
    [('t1.Country', '!=', 't2.Country'), ('t1.InvoiceDate', '!=', 't2.InvoiceDate'), ('t1.Description', '!=', 't2.Description'), ('t1.CustomerID', '!=', 't2.CustomerID'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Quantity', '<', 't2.Quantity'), ('t1.UnitPrice', '<', 't2.UnitPrice')],
    [('t1.Country', '!=', 't2.Country'), ('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.Description', '==', 't2.Description')],
    [('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '==', 't2.CustomerID'), ('t1.UnitPrice', '<', 't2.UnitPrice'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.Description', '!=', 't2.Description'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Country', '!=', 't2.Country'), ('t1.InvoiceNo', '==', 't2.InvoiceNo')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.InvoiceDate', '!=', 't2.InvoiceDate'), ('t1.Description', '!=', 't2.Description'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.InvoiceNo', '==', 't2.InvoiceNo'), ('t1.InvoiceDate', '!=', 't2.InvoiceDate'), ('t1.StockCode', '!=', 't2.StockCode'), ('t1.Description', '==', 't2.Description')],
    [('t1.Country', '!=', 't2.Country'), ('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Country', '!=', 't2.Country'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Country', '!=', 't2.Country'), ('t1.UnitPrice', '==', 't2.UnitPrice'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '==', 't2.CustomerID'), ('t1.Quantity', '!=', 't2.Quantity')],
    [('t1.Country', '!=', 't2.Country'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '==', 't2.CustomerID'), ('t1.StockCode', '==', 't2.StockCode')],
    [('t1.Country', '!=', 't2.Country'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.CustomerID', '==', 't2.CustomerID'), ('t1.Description', '==', 't2.Description')],
    [('t1.UnitPrice', '!=', 't2.UnitPrice'), ('t1.Description', '!=', 't2.Description'), ('t1.InvoiceDate', '==', 't2.InvoiceDate'), ('t1.Quantity', '==', 't2.Quantity'), ('t1.StockCode', '==', 't2.StockCode')],
]
