# Parsed denial constraints for Tax
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.city', '!=', 't2.city'), ('t1.zip', '==', 't2.zip')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.state', '!=', 't2.state')],
    [('t1.state', '!=', 't2.state'), ('t1.zip', '==', 't2.zip')],
    [('t1.single_exemp', '>', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp')],
    [('t1.single_exemp', '<', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.fname', '==', 't2.fname'), ('t1.gender', '!=', 't2.gender')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.phone', '==', 't2.phone')],
    [('t1.phone', '==', 't2.phone'), ('t1.city', '==', 't2.city')],
    [('t1.fname', '==', 't2.fname'), ('t1.phone', '==', 't2.phone')],
    [('t1.lname', '==', 't2.lname'), ('t1.phone', '==', 't2.phone')],
    [('t1.phone', '==', 't2.phone'), ('t1.zip', '==', 't2.zip')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '>', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '<', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.has_child', '==', 't2.has_child'), ('t1.child_exemp', '!=', 't2.child_exemp')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.has_child', '==', 't2.has_child'), ('t1.child_exemp', '!=', 't2.child_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.has_child', '==', 't2.has_child'), ('t1.child_exemp', '!=', 't2.child_exemp')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '==', 't2.married_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.single_exemp', '==', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '==', 't2.married_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.single_exemp', '==', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '==', 't2.married_exemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.single_exemp', '==', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
    [('t1.area_code', '==', 't2.area_code'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.zip', '==', 't2.zip'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '<', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp')],
    [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '>', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.has_child', '==', 't2.has_child'), ('t1.child_exemp', '>', 't2.child_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.has_child', '==', 't2.has_child'), ('t1.child_exemp', '<', 't2.child_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '>', 't2.single_exemp')],
    [('t1.state', '==', 't2.state'), ('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '<', 't2.single_exemp')],
]
