
# =========================
# TAX
# =========================
denial_constraints = [[('t1.city', '!=', 't2.city'), ('t1.zip', '==', 't2.zip')],
 [('t1.area_code', '==', 't2.area_code'), ('t1.state', '!=', 't2.state')],
 [('t1.state', '!=', 't2.state'), ('t1.zip', '==', 't2.zip')],
 [('t1.single_exemp', '>', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp')],
 [('t1.single_exemp', '<', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '<', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.child_exemp', '>', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.child_exemp', '<', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '<', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '>', 't2.married_exemp'), ('t1.child_exemp', '<', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.single_exemp', '!=', 't2.single_exemp'), ('t1.married_exemp', '<', 't2.married_exemp'), ('t1.child_exemp', '<', 't2.child_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp'), ('t1.single_exemp', '>', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp'), ('t1.single_exemp', '<', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '!=', 't2.married_exemp'), ('t1.child_exemp', '<', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '>', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '<', 't2.married_exemp'), ('t1.child_exemp', '!=', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')],
 [('t1.marital_status', '==', 't2.marital_status'), ('t1.married_exemp', '>', 't2.married_exemp'), ('t1.child_exemp', '>', 't2.child_exemp'), ('t1.single_exemp', '!=', 't2.single_exemp')]]
