#!/usr/bin/env python3
"""
plot_mask_size_vs_leakage.py

Plots:
    mask_size  vs  leakage

Input:
    CSV generated by export_all_masks_all_datasets_streaming.py

Usage:
    python plot_mask_size_vs_leakage.py all_masks_all_datasets_with_leakage.csv

Output:
    mask_size_vs_leakage.png
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------

INPUT_CSV = sys.argv[1] if len(sys.argv) > 1 else "all_masks_all_datasets_with_leakage.csv"
OUTPUT_PNG = "mask_size_vs_leakage.png"

# Plot style
PLOT_MEAN_ONLY = True     # True = average leakage per mask size
PLOT_SCATTER = False     # True = raw scatter (can be huge)

FIGSIZE = (6, 4)
ALPHA_SCATTER = 0.05
LINEWIDTH = 2.0

# ------------------------------------------------------------------------------
# Load data
# ------------------------------------------------------------------------------

print(f"[INFO] Loading CSV: {INPUT_CSV}")
df = pd.read_csv(INPUT_CSV)

required_cols = {"dataset", "mask_size", "leakage"}
missing = required_cols - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns: {missing}")

# ------------------------------------------------------------------------------
# Aggregate
# ------------------------------------------------------------------------------

if PLOT_MEAN_ONLY:
    agg = (
        df
        .groupby(["dataset", "mask_size"], as_index=False)
        .agg(mean_leakage=("leakage", "mean"))
    )

# ------------------------------------------------------------------------------
# Plot
# ------------------------------------------------------------------------------

plt.figure(figsize=FIGSIZE)

for dataset, g in (agg.groupby("dataset") if PLOT_MEAN_ONLY else df.groupby("dataset")):
    if PLOT_MEAN_ONLY:
        plt.plot(
            g["mask_size"],
            g["mean_leakage"],
            marker="o",
            linewidth=LINEWIDTH,
            label=dataset,
        )
    if PLOT_SCATTER:
        plt.scatter(
            g["mask_size"],
            g["leakage"],
            alpha=ALPHA_SCATTER,
            s=6,
            label=f"{dataset} (scatter)",
        )

plt.xlabel("Mask size |M|")
plt.ylabel("Leakage L(M)")
plt.title("Mask Size vs Leakage")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.savefig(OUTPUT_PNG, dpi=300)
plt.close()

print(f"[DONE] Saved plot → {OUTPUT_PNG}")
